name: CI/CD
 
on:
  push:
    branches:
      - main
 
jobs:
 
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: |
        docker build -t myapp:${{ github.sha }} .
    - name: Run Unit Tests
      run: |
        docker run myapp:${{ github.sha }} npm test
    - name: Push Docker Image
      if: success()
      run: |  
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push myapp:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      run: |
        docker pull myapp:${{ github.sha }}
        docker run -d --name staging myapp:${{ github.sha }}
    - name: Smoke Tests
      run: |
        # run smoke tests against staging
    - name: Deploy to Production
      if: success()  
      run: |
        docker pull myapp:${{ github.sha }}
        docker stop production && docker rm production
        docker run -d --name production myapp:${{ github.sha }}
